import { DocumentTypeDefinition, DocumentTypeSlug, DocumentCategory } from './types';
export type { DocumentTypeDefinition };

export const DOCUMENT_REGISTRY: Record<DocumentTypeSlug, DocumentTypeDefinition> = {
  jha: {
    type: 'jha',
    slug: 'jha',
    name: 'Job Hazard Analysis (JHA)',
    code: 'SAF-JHA',
    description: 'Sequenced task breakdown, OSHA hazard identification, hierarchy of controls, and mandatory PPE for field operations.',
    category: 'safety',
    version: '1.0',
    supportsAi: true,
    supportsTemplate: true,
    supportsProjectContext: true,
    supportsContractorContext: true,
    requiresHumanReview: true,
    readinessRelevance: true,
    active: true,
  },
  jsa: {
    type: 'jsa',
    slug: 'jsa',
    name: 'Job Safety Analysis (JSA)',
    code: 'SAF-JSA',
    description: 'Activity-level hazard evaluation, preventive controls, and responsible persons for specific trade tasks.',
    category: 'safety',
    version: '1.0',
    supportsAi: true,
    supportsTemplate: true,
    supportsProjectContext: true,
    supportsContractorContext: true,
    requiresHumanReview: true,
    readinessRelevance: true,
    active: true,
  },
  'safety-plan': {
    type: 'safety-plan',
    slug: 'safety-plan',
    name: 'Site-Specific Safety Plan (HASP)',
    code: 'SAF-HASP',
    description: 'Comprehensive site safety rules, emergency contacts, hazard communications, and incident response procedures.',
    category: 'safety',
    version: '1.0',
    supportsAi: true,
    supportsTemplate: true,
    supportsProjectContext: true,
    supportsContractorContext: true,
    requiresHumanReview: true,
    readinessRelevance: true,
    active: true,
  },
  'toolbox-talk': {
    type: 'toolbox-talk',
    slug: 'toolbox-talk',
    name: 'Field Toolbox Talk',
    code: 'SAF-TBT',
    description: 'Concise, focused on-site safety briefing with core hazards, discussion questions, and worker sign-off roster.',
    category: 'safety',
    version: '1.0',
    supportsAi: true,
    supportsTemplate: true,
    supportsProjectContext: true,
    supportsContractorContext: true,
    requiresHumanReview: false,
    readinessRelevance: true,
    active: true,
  },
  quote: {
    type: 'quote',
    slug: 'quote',
    name: 'Contractor Quote',
    code: 'COM-QUO',
    description: 'Detailed commercial pricing with structured line items, quantities, units, configurable tax, and clear acceptance terms.',
    category: 'commercial',
    version: '1.0',
    supportsAi: false, // Quotes are deterministic financial schedules
    supportsTemplate: true,
    supportsProjectContext: true,
    supportsContractorContext: true,
    requiresHumanReview: false,
    readinessRelevance: false,
    active: true,
  },
  proposal: {
    type: 'proposal',
    slug: 'proposal',
    name: 'Commercial Bid Proposal',
    code: 'COM-PRP',
    description: 'Full competitive proposal with scope narrative, technical approach, key milestones, commercial summary, and credentials.',
    category: 'commercial',
    version: '1.0',
    supportsAi: true,
    supportsTemplate: true,
    supportsProjectContext: true,
    supportsContractorContext: true,
    requiresHumanReview: true,
    readinessRelevance: false,
    active: true,
  },
  'scope-of-work': {
    type: 'scope-of-work',
    slug: 'scope-of-work',
    name: 'Scope of Work (SOW)',
    code: 'COM-SOW',
    description: 'Explicit contract deliverables, included/excluded scopes, site conditions, craftsmanship standards, and change control clauses.',
    category: 'commercial',
    version: '1.0',
    supportsAi: true,
    supportsTemplate: true,
    supportsProjectContext: true,
    supportsContractorContext: true,
    requiresHumanReview: true,
    readinessRelevance: false,
    active: true,
  },
  'change-order': {
    type: 'change-order',
    slug: 'change-order',
    name: 'Contract Change Order',
    code: 'COM-CHO',
    description: 'Formal contract modification detailing scope alterations, cost adjustments, schedule impact, and required client sign-off.',
    category: 'commercial',
    version: '1.0',
    supportsAi: true,
    supportsTemplate: true,
    supportsProjectContext: true,
    supportsContractorContext: true,
    requiresHumanReview: true,
    readinessRelevance: false,
    active: true,
  },
  'daily-report': {
    type: 'daily-report',
    slug: 'daily-report',
    name: 'Daily Field Log & Report',
    code: 'OPS-DLR',
    description: 'Daily operational log tracking crew headcount, work completed, equipment on site, weather conditions, delays, and supervisor sign-off.',
    category: 'operations',
    version: '1.0',
    supportsAi: false,
    supportsTemplate: true,
    supportsProjectContext: true,
    supportsContractorContext: true,
    requiresHumanReview: true,
    readinessRelevance: false,
    active: true,
  },
};

export const ALL_DOCUMENT_TYPES = Object.values(DOCUMENT_REGISTRY);

export function getDocumentsByCategory(category: DocumentCategory): DocumentTypeDefinition[] {
  return ALL_DOCUMENT_TYPES.filter((doc) => doc.category === category);
}

export function getDocumentDefinition(type: DocumentTypeSlug): DocumentTypeDefinition | undefined {
  return DOCUMENT_REGISTRY[type];
}
