/**
 * AVORRIA MONTHLY USAGE METERING
 *
 * Tracks document generation counts per organization on a monthly cycle
 * to enforce Free Starter quotas (3 documents/month) while resetting each calendar month.
 */

import fs from 'fs';
import path from 'path';

interface UsageStore {
  [orgId: string]: {
    [monthKey: string]: number;
  };
}

let memoryUsage: UsageStore = {};

const DATA_DIR = path.join(process.cwd(), '.data');
const USAGE_PATH = path.join(DATA_DIR, 'usage-store.json');

function loadUsageStore(): UsageStore {
  try {
    if (fs.existsSync(USAGE_PATH)) {
      const data = fs.readFileSync(USAGE_PATH, 'utf-8');
      memoryUsage = JSON.parse(data);
      return memoryUsage;
    }
  } catch {
    // Fallback to in-memory
  }
  return memoryUsage;
}

function saveUsageStore(): void {
  try {
    if (!fs.existsSync(DATA_DIR)) {
      fs.mkdirSync(DATA_DIR, { recursive: true });
    }
    fs.writeFileSync(USAGE_PATH, JSON.stringify(memoryUsage, null, 2), 'utf-8');
  } catch {
    // In-memory retains current state on read-only filesystems
  }
}

export function getCurrentMonthKey(): string {
  const d = new Date();
  const year = d.getUTCFullYear();
  const month = String(d.getUTCMonth() + 1).padStart(2, '0');
  return `${year}-${month}`;
}

/**
 * Gets the number of documents generated by this org in the given month (defaults to current).
 */
export async function getMonthlyGenerationUsage(
  orgId: string,
  monthKey = getCurrentMonthKey()
): Promise<number> {
  const store = loadUsageStore();
  return store[orgId]?.[monthKey] || 0;
}

/**
 * Increments the document generation counter for this org in the given month.
 */
export async function incrementMonthlyGenerationUsage(
  orgId: string,
  monthKey = getCurrentMonthKey()
): Promise<number> {
  const store = loadUsageStore();
  if (!store[orgId]) {
    store[orgId] = {};
  }
  const current = store[orgId][monthKey] || 0;
  const next = current + 1;
  store[orgId][monthKey] = next;
  saveUsageStore();
  return next;
}

/**
 * Resets the usage counter for testing or new billing cycles.
 */
export async function resetMonthlyGenerationUsage(
  orgId: string,
  monthKey = getCurrentMonthKey()
): Promise<void> {
  const store = loadUsageStore();
  if (store[orgId]) {
    delete store[orgId][monthKey];
    saveUsageStore();
  }
}
